# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qjMqPHKK9BAjVKEOqFg6hvMmvXBexP5u
"""

!pip install langchain==0.1.17 \
             langchain-community==0.0.36 \
             langchain-huggingface==0.0.3 \
             faiss-cpu \
             sentence-transformers \
             transformers \
             pypdf

from langchain_community.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings, HuggingFacePipeline
from langchain.chains import RetrievalQA

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline

pdf_path = input("Enter path to PDF file: ")
loader = PyPDFLoader(pdf_path)
documents = loader.load()


text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

docs = text_splitter.split_documents(documents)

print(f"Total chunks created: {len(docs)}")

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vectorstore = FAISS.from_documents(docs, embeddings)

retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

print("FAISS index created successfully.")

model_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

pipe = pipeline(
    "text2text-generation",
    model=model,
    tokenizer=tokenizer,
    max_length=256
)

llm = HuggingFacePipeline(pipeline=pipe)

print("LLM loaded.")

from langchain.prompts import PromptTemplate

template = """
Use the following context to answer the question.
If the answer is not in the context, say you don't know.

Context:
{context}

Question:
{question}

Answer:
"""

prompt = PromptTemplate(
    template=template,
    input_variables=["context", "question"]
)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever,
    return_source_documents=True,
    chain_type_kwargs={"prompt": prompt}
)

print("RAG chain ready.")

result = qa_chain({"query": "What is this document about?"})

print("Answer:\n", result["result"])

print("\n--- Source Documents Used ---\n")
for i, doc in enumerate(result["source_documents"]):
    print(f"Source {i+1}:")
    print(doc.page_content[:300])
    print("\n")